name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install modules
      run: |
        npm install -g npm@7
        npm ci
    - name: Run code quality tests
      run: npm run lint:eslint -- --format=compact
    - name: Run types tests
      run: npm run lint:types
    - name: Run tests
      run: npm run test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: unittests
        fail_ci_if_error: false
        path_to_write_report: ./codecov_report.txt
        verbose: true
