name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:

  Code-Quality:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Install modules
      run: npm install
    - name: Run code quality tests
      run: npm run lint:eslint -- --format=compact
    - name: Run types tests
      run: npm run lint:types

  Unit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test -- -- -i --coverage || npm run test -- -- -i --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: unittests
        fail_ci_if_error: false
        path_to_write_report: ./codecov_report.txt
        verbose: true
