name: Tests
on: push
jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Upload to Codecov
      run: npx codecov --disable=detect --commit=$GITHUB_SHA --branch=${GITHUB_REF#refs/heads/}
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
